version: '3.7'

# do not forget to add in /etc/hosts (see but it should work without...) 
# 127.0.0.1 zookeeper-1 zookeeper-2 zookeeper-3
# 127.0.0.1 kafka-1 kafka-2 kafka-3


services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper-1
    user: root
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./zk/zk-data1:/var/lib/zookeeper/data
      - ./zk/zk-logs1:/var/lib/zookeeper/log  

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper-2
    user: root
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./zk/zk-data2:/var/lib/zookeeper/data
      - ./zk/zk-logs2:/var/lib/zookeeper/log  

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper-3
    user: root
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./zk/zk-data3:/var/lib/zookeeper/data
      - ./zk/zk-logs3:/var/lib/zookeeper/log  

  kafka-1:
    # image: confluentinc/cp-kafka:latest
    image: confluentinc/cp-server:7.0.1
    hostname: kafka-1
    user: root
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_JMX_HOSTNAME: "kafka-1"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka-1
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.rmi.port=9999
      -Dcom.sun.management.jmxremote.port=9999
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ./kafka/kafka-data1:/var/lib/kafka/data
      - ./kafka/kafka-log1:/var/log/kafka
    healthcheck:
      test: ["CMD", "nc", "-vz", "kafka-1", "19092"]
      interval: 30s
      timeout: 10s
      retries: 4

  kafka-2:
    # image: confluentinc/cp-kafka:latest
    image: confluentinc/cp-server:7.0.1
    hostname: kafka-2
    user: root
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_JMX_HOSTNAME: "kafka-2"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka-2
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.rmi.port=9999
      -Dcom.sun.management.jmxremote.port=9999
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false"    
    volumes:
      - ./kafka/kafka-data2:/var/lib/kafka/data
      - ./kafka/kafka-log2:/var/log/kafka
    healthcheck:
      test: ["CMD", "nc", "-vz", "kafka-2", "29092"]
      interval: 30s
      timeout: 10s
      retries: 4


  kafka-3:
    # image: confluentinc/cp-kafka:latest
    image: confluentinc/cp-server:7.0.1
    hostname: kafka-3
    user: root
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_JMX_HOSTNAME: "kafka-3"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka-3
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.rmi.port=9999
      -Dcom.sun.management.jmxremote.port=9999
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ./kafka/kafka-data3:/var/lib/kafka/data
      - ./kafka/kafka-log3:/var/log/kafka
    healthcheck:
      test: ["CMD", "nc", "-vz", "kafka-3", "39092"]
      interval: 30s
      timeout: 10s
      retries: 4

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    user: root
    environment:
      ZK_HOSTS: "zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    volumes:
      - ./kafka/manager:/kafka-manager/logs

  schema-registry-1:
    image: confluentinc/cp-schema-registry:7.1.0
    hostname: schema-registry-1
    container_name: schema-registry-1
    user: root
    depends_on:
      kafka-1:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-1:19092,kafka-2:29092,kafka-3:39092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    healthcheck:
      test: nc -z localhost 8081 || exit -1 
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    volumes:
      - ./kafka/registry1:/etc/schema-registry

  schema-registry-2:
    image: confluentinc/cp-schema-registry:7.1.0
    hostname: schema-registry-2
    container_name: schema-registry-2
    user: root
    depends_on:
      kafka-2:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-2
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-1:19092,kafka-2:29092,kafka-3:39092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082
    healthcheck:
      test: nc -z localhost 8082 || exit -1 
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    volumes:
      - ./kafka/registry2:/etc/schema-registry

  schema-registry-3:
    image: confluentinc/cp-schema-registry:7.1.0
    hostname: schema-registry-3
    container_name: schema-registry-3
    user: root
    depends_on:
      kafka-3:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-3
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-1:19092,kafka-2:29092,kafka-3:39092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8083
    healthcheck:
      test: nc -z localhost 8083 || exit -1 
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    volumes:
      - ./kafka/registry3:/etc/schema-registry



